In [14]:
import pandas as pd
import glob

dfs = []

# Read all Excel files
for f in glob.glob("/Users/zack/Documents/6300/ttc_bus_delay_data/*.xlsx"):
    df = pd.read_excel(f)
    dfs.append(df)

# Read CSV file and rename columns to match Excel
csv_df = pd.read_csv("/Users/zack/Documents/6300/ttc_bus_delay_data/TTC Bus Delay Data since 2025.csv")
csv_df.rename(columns={
    "_id": "ID",
    "Date": "Report Date",
    "Line": "Route",
    "Station": "Location",
    "Code": "Incident",
    "Bound": "Direction"
}, inplace=True)

dfs.append(csv_df)

# Combine all into one DataFrame
combined_df = pd.concat(dfs, ignore_index=True, sort=False)



# Check first 10 rows
print(combined_df.head(10))

           Report Date Route      Time     Day                 Location  \
0  2016-01-01 00:00:00   123  00:10:00  Friday          LONGBRANCH LOOP
1  2016-01-01 00:00:00   112  00:25:00  Friday              KIPLING STN
2  2016-01-01 00:00:00   736  01:03:00  Friday  ROYAL YORK AT ROMNEY RD
3  2016-01-01 00:00:00    94  01:10:00  Friday            Ossington Stn
4  2016-01-01 00:00:00    89  01:30:00  Friday            Keele Station
5  2016-01-01 00:00:00    64  01:50:00  Friday                 main Stn
6  2016-01-01 00:00:00    60  02:00:00  Friday             steeles loop
7  2016-01-01 00:00:00    87  02:05:00  Friday                 Main stn
8  2016-01-01 00:00:00   116  02:10:00  Friday     Markham and Eglinton
9  2016-01-01 00:00:00    87  02:35:00  Friday                 Main Stn

             Incident  Min Delay  Min Gap Direction  Vehicle  Delay  Gap Date  \
0          Mechanical       24.0     48.0       N/B   8043.0    NaN  NaN  NaT
1          Mechanical       18.0     36.0       N/B   8023.0    NaN  NaN  NaT
2       Investigation       20.0     40.0       N/B   8032.0    NaN  NaN  NaT
3          Mechanical       10.0     20.0        SB   7745.0    NaN  NaN  NaT
4          Mechanical       10.0     20.0        NB   1622.0    NaN  NaN  NaT
5          Mechanical       30.0     60.0        NB   7801.0    NaN  NaN  NaT
6          Mechanical       11.0     22.0       e/b   1313.0    NaN  NaN  NaT
7  Utilized Off Route       10.0     20.0        NB   7707.0    NaN  NaN  NaT
8          Mechanical       10.0     20.0         E   7603.0    NaN  NaN  NaT
9          Mechanical       10.0     20.0        NB   7829.0    NaN  NaN  NaT

   ID
0 NaN
1 NaN
2 NaN
3 NaN
4 NaN
5 NaN
6 NaN
7 NaN
8 NaN
9 NaN

In [15]:
combined_df['Report Date'] = combined_df['Report Date'].fillna(combined_df['Date'])
#merge the Date column with Report Date

combined_df = combined_df.drop(columns=['Date'])
#delete the Date column

combined_df['Report Date'] = pd.to_datetime(combined_df['Report Date'], errors='coerce')
# convert the date type to actual date type instead of string type

combined_df = combined_df.sort_values(by='Report Date', ascending=True)
#sort the date into ascending order

combined_df = combined_df.reset_index(drop=True)
# reset the index

combined_df.head(10)

,Report Date,Route,Time,Day,Location,Incident,Min Delay,Min Gap,Direction,Vehicle,Delay,Gap,ID
0,2014-01-01,95,00:23:00,Wednesday,York Mills station,Mechanical,10.0,20.0,E,1734.0,NaN,NaN,NaN
1,2014-01-01,7,14:19:00,Wednesday,Bathurst and Wilson,Mechanical,9.0,18.0,N,NaN,NaN,NaN,NaN
2,2014-01-01,46,14:05:00,Wednesday,Kipling Station,Mechanical,15.0,30.0,N,7925.0,NaN,NaN,NaN
3,2014-01-01,90,13:50:00,Wednesday,St.Clair west stn,Mechanical,15.0,30.0,N,1780.0,NaN,NaN,NaN
4,2014-01-01,26,13:47:00,Wednesday,Annette and High Park Ave.,Investigation,30.0,60.0,E,8057.0,NaN,NaN,NaN
5,2014-01-01,106,13:45:00,Wednesday,Downsview stn,Mechanical,15.0,30.0,N,8358.0,NaN,NaN,NaN
6,2014-01-01,89,12:31:00,Wednesday,Albion and Weston Rd,Late Leaving Garage,9.0,18.0,s/b,1048.0,NaN,NaN,NaN
7,2014-01-01,85,12:28:00,Wednesday,Metro Zoo,Late Leaving Garage,5.0,10.0,WB,1717.0,NaN,NaN,NaN
8,2014-01-01,9,12:21:00,Wednesday,Warden Station,Late Leaving Garage,20.0,40.0,B/W,7882.0,NaN,NaN,NaN
9,2014-01-01,190,12:17:00,Wednesday,Scarborough town centre,Late Leaving Garage,10.0,20.0,wb,1758.0,NaN,NaN,NaN

In [ ]:
df_2016 = combined_df[combined_df['Report Date'].dt.year == 2016]

df_2014 = combined_df[combined_df['Report Date'].dt.year == 2014]

df_2015 = combined_df[combined_df['Report Date'].dt.year == 2015]

print(df_2014.tail(10))

print(df_2014.tail(10))

     Report Date Route      Time     Day  \
9812  2014-01-31    79  05:20:00  Friday
9813  2014-01-31   196  05:34:00  Friday
9814  2014-01-31    36  05:45:00  Friday
9815  2014-01-31    36  05:28:00  Friday
9816  2014-01-31    36  05:45:00  Friday
9817  2014-01-31   131  05:48:00  Friday
9818  2014-01-31    59  12:30:00  Friday
9819  2014-01-31   165  05:55:00  Friday
9820  2014-01-31    37  05:56:00  Friday
9821  2014-01-31    95  06:01:00  Friday

                                    Location            Incident  Min Delay  \
9812                         Pine / Lawrence          Mechanical       20.0
9813                       Downsview Staiton  Utilized Off Route        3.0
9814                       Finch station 36F          Mechanical       14.0
9815     Finch & Arrow (ARG 5.50a-9.47a ARG)          Mechanical       10.0
9816                      Finch station  36B          Mechanical        8.0
9817  Morningview Trail & Morningside Avenue          Mechanical        8.0
9818      Lawrence West station - Weston/Oak       General Delay       30.0
9819                          Finch & Weston          Mechanical       10.0
9820                                    FIIS          Mechanical        2.0
9821                   Ellesmere and McCowan          Mechanical        3.0

      Min Gap Direction  Vehicle  Delay  Gap  ID
9812     40.0         s   1599.0    NaN  NaN NaN
9813      5.0         n   8386.0    NaN  NaN NaN
9814     28.0         W   7958.0    NaN  NaN NaN
9815     21.0         E   7945.0    NaN  NaN NaN
9816     18.0         W   1270.0    NaN  NaN NaN
9817     16.0        WB   1087.0    NaN  NaN NaN
9818     41.0       B/W      NaN    NaN  NaN NaN
9819     17.0         N   7241.0    NaN  NaN NaN
9820      5.0         S   1313.0    NaN  NaN NaN
9821      6.0        WB   1070.0    NaN  NaN NaN

In [ ]:
combined_df['Min Gap'] = combined_df['Min Gap'].fillna(combined_df['Gap'])

combined_df = combined_df.drop(columns=['Gap'])

#merge the Gap and Min Gap

In [ ]:
combined_df['Min Delay'] = combined_df['Min Delay'].fillna(combined_df['Delay'])

combined_df = combined_df.drop(columns=['Delay', 'ID'])

In [ ]:

# Ensure Report Date is datetime
combined_df['Report Date'] = pd.to_datetime(combined_df['Report Date'], errors='coerce')

# Create Year column
combined_df['Year'] = combined_df['Report Date'].dt.year

# Show first 10 rows for each year

In [30]:
combined_df.head(100)

,Report Date,Route,Time,Day,Location,Incident,Min Delay,Min Gap,Direction,Vehicle,Year
0,2014-01-01,95,00:23:00,Wednesday,York Mills station,Mechanical,10.0,20.0,E,1734.0,2014
1,2014-01-01,7,14:19:00,Wednesday,Bathurst and Wilson,Mechanical,9.0,18.0,N,NaN,2014
2,2014-01-01,46,14:05:00,Wednesday,Kipling Station,Mechanical,15.0,30.0,N,7925.0,2014
3,2014-01-01,90,13:50:00,Wednesday,St.Clair west stn,Mechanical,15.0,30.0,N,1780.0,2014
4,2014-01-01,26,13:47:00,Wednesday,Annette and High Park Ave.,Investigation,30.0,60.0,E,8057.0,2014
...,...,...,...,...,...,...,...,...,...,...,...
95,2014-01-01,58,06:54:00,Wednesday,T1 - Airport,Late Leaving Garage,20.0,42.0,E,1568.0,2014
96,2014-01-01,300,06:37:00,Wednesday,Danforth and Danforth,Late Leaving Garage,6.0,12.0,EB,7592.0,2014
97,2014-01-01,86,09:24:00,Wednesday,Kennedy Stn,Mechanical,7.0,14.0,E,7522.0,2014
98,2014-01-01,116,09:22:00,Wednesday,Morningside & Nightstar,Mechanical,11.0,15.0,S,7460.0,2014
99,2014-01-01,91,09:20:00,Wednesday,Bermondsay / Eglinton,Mechanical,20.0,40.0,Nnb,7861.0,2014

In [31]:
# Save cleaned dataframe to a new CSV file
combined_df.to_csv("cleaned_transport_data.csv", index=False)